/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6FAxEAZuSy8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Progress } from "@/components/ui/progress"
import LeftPanel from "./leftpanel"
import BottomPanel from "./bottompanel"
import RightPanel from "./rightpanel"
import TopPanel from "./toppanel"
export default function Generator() {
  return (
    <div key="1" className="flex flex-col h-screen">
      <TopPanel />
      <div className="flex flex-1 overflow-hidden">
        <LeftPanel />
        <RightPanel />
      </div>
      <BottomPanel />
    </div>
  )
}
